version: '2'

services:

  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    
  web:
    build: ./app
    env_file: .env
    command: bash -c "python manage.py runserver 0:8000"
    volumes:
      - ./app/:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  
  redis:
    build: ./redis
    volumes:
      - ./redis/:/redis
    ports:
      - "6379:6379" 
    

volumes:
  postgres_data:     